project_name: ukfast
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  ldflags:
    - -s -X main.VERSION={{.Version}} -X main.BUILDDATE={{.Date}}
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archives:
- format_overrides: 
  - goos: windows 
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  disable: true
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

