version: 2
project_name: ans
builds:
- env:
  - CGO_ENABLED=0
  flags:
    - -trimpath
  ldflags:
    - -s -X main.VERSION={{.Version}} -X main.BUILDDATE={{.Date}}
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
  ignore:
    - goos: windows
      goarch: arm
archives:
- format_overrides: 
  - goos: windows 
    formats: zip
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
snapshot:
  version_template: "{{ .Tag }}-next"
release:
  github:
    owner: ans-group
    name: cli
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

