project_name: ans
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -X main.VERSION={{.Version}} -X main.BUILDDATE={{.Date}}
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
archives:
- format_overrides: 
  - goos: windows 
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: ans-group
    name: cli
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

