// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ukfast/sdk-go/pkg/service/ltaas (interfaces: LTaaSService)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	connection "github.com/ukfast/sdk-go/pkg/connection"
	ltaas "github.com/ukfast/sdk-go/pkg/service/ltaas"
	reflect "reflect"
)

// MockLTaaSService is a mock of LTaaSService interface
type MockLTaaSService struct {
	ctrl     *gomock.Controller
	recorder *MockLTaaSServiceMockRecorder
}

// MockLTaaSServiceMockRecorder is the mock recorder for MockLTaaSService
type MockLTaaSServiceMockRecorder struct {
	mock *MockLTaaSService
}

// NewMockLTaaSService creates a new mock instance
func NewMockLTaaSService(ctrl *gomock.Controller) *MockLTaaSService {
	mock := &MockLTaaSService{ctrl: ctrl}
	mock.recorder = &MockLTaaSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLTaaSService) EXPECT() *MockLTaaSServiceMockRecorder {
	return m.recorder
}

// CreateDomain mocks base method
func (m *MockLTaaSService) CreateDomain(arg0 ltaas.CreateDomainRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDomain", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDomain indicates an expected call of CreateDomain
func (mr *MockLTaaSServiceMockRecorder) CreateDomain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDomain", reflect.TypeOf((*MockLTaaSService)(nil).CreateDomain), arg0)
}

// CreateJob mocks base method
func (m *MockLTaaSService) CreateJob(arg0 ltaas.CreateJobRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob
func (mr *MockLTaaSServiceMockRecorder) CreateJob(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockLTaaSService)(nil).CreateJob), arg0)
}

// DeleteDomain mocks base method
func (m *MockLTaaSService) DeleteDomain(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDomain", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDomain indicates an expected call of DeleteDomain
func (mr *MockLTaaSServiceMockRecorder) DeleteDomain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDomain", reflect.TypeOf((*MockLTaaSService)(nil).DeleteDomain), arg0)
}

// DeleteJob mocks base method
func (m *MockLTaaSService) DeleteJob(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJob indicates an expected call of DeleteJob
func (mr *MockLTaaSServiceMockRecorder) DeleteJob(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockLTaaSService)(nil).DeleteJob), arg0)
}

// GetDomain mocks base method
func (m *MockLTaaSService) GetDomain(arg0 string) (ltaas.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomain", arg0)
	ret0, _ := ret[0].(ltaas.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomain indicates an expected call of GetDomain
func (mr *MockLTaaSServiceMockRecorder) GetDomain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomain", reflect.TypeOf((*MockLTaaSService)(nil).GetDomain), arg0)
}

// GetDomains mocks base method
func (m *MockLTaaSService) GetDomains(arg0 connection.APIRequestParameters) ([]ltaas.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomains", arg0)
	ret0, _ := ret[0].([]ltaas.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomains indicates an expected call of GetDomains
func (mr *MockLTaaSServiceMockRecorder) GetDomains(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomains", reflect.TypeOf((*MockLTaaSService)(nil).GetDomains), arg0)
}

// GetDomainsPaginated mocks base method
func (m *MockLTaaSService) GetDomainsPaginated(arg0 connection.APIRequestParameters) (*ltaas.PaginatedDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomainsPaginated", arg0)
	ret0, _ := ret[0].(*ltaas.PaginatedDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomainsPaginated indicates an expected call of GetDomainsPaginated
func (mr *MockLTaaSServiceMockRecorder) GetDomainsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomainsPaginated", reflect.TypeOf((*MockLTaaSService)(nil).GetDomainsPaginated), arg0)
}

// GetJob mocks base method
func (m *MockLTaaSService) GetJob(arg0 string) (ltaas.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", arg0)
	ret0, _ := ret[0].(ltaas.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob
func (mr *MockLTaaSServiceMockRecorder) GetJob(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockLTaaSService)(nil).GetJob), arg0)
}

// GetJobResults mocks base method
func (m *MockLTaaSService) GetJobResults(arg0 string) (ltaas.JobResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobResults", arg0)
	ret0, _ := ret[0].(ltaas.JobResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobResults indicates an expected call of GetJobResults
func (mr *MockLTaaSServiceMockRecorder) GetJobResults(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobResults", reflect.TypeOf((*MockLTaaSService)(nil).GetJobResults), arg0)
}

// GetJobs mocks base method
func (m *MockLTaaSService) GetJobs(arg0 connection.APIRequestParameters) ([]ltaas.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobs", arg0)
	ret0, _ := ret[0].([]ltaas.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobs indicates an expected call of GetJobs
func (mr *MockLTaaSServiceMockRecorder) GetJobs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobs", reflect.TypeOf((*MockLTaaSService)(nil).GetJobs), arg0)
}

// GetJobsPaginated mocks base method
func (m *MockLTaaSService) GetJobsPaginated(arg0 connection.APIRequestParameters) (*ltaas.PaginatedJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobsPaginated", arg0)
	ret0, _ := ret[0].(*ltaas.PaginatedJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobsPaginated indicates an expected call of GetJobsPaginated
func (mr *MockLTaaSServiceMockRecorder) GetJobsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobsPaginated", reflect.TypeOf((*MockLTaaSService)(nil).GetJobsPaginated), arg0)
}

// GetTest mocks base method
func (m *MockLTaaSService) GetTest(arg0 string) (ltaas.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTest", arg0)
	ret0, _ := ret[0].(ltaas.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTest indicates an expected call of GetTest
func (mr *MockLTaaSServiceMockRecorder) GetTest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTest", reflect.TypeOf((*MockLTaaSService)(nil).GetTest), arg0)
}

// GetTests mocks base method
func (m *MockLTaaSService) GetTests(arg0 connection.APIRequestParameters) ([]ltaas.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTests", arg0)
	ret0, _ := ret[0].([]ltaas.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTests indicates an expected call of GetTests
func (mr *MockLTaaSServiceMockRecorder) GetTests(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTests", reflect.TypeOf((*MockLTaaSService)(nil).GetTests), arg0)
}

// GetTestsPaginated mocks base method
func (m *MockLTaaSService) GetTestsPaginated(arg0 connection.APIRequestParameters) (*ltaas.PaginatedTest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestsPaginated", arg0)
	ret0, _ := ret[0].(*ltaas.PaginatedTest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTestsPaginated indicates an expected call of GetTestsPaginated
func (mr *MockLTaaSServiceMockRecorder) GetTestsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestsPaginated", reflect.TypeOf((*MockLTaaSService)(nil).GetTestsPaginated), arg0)
}

// VerifyDomainByDNS mocks base method
func (m *MockLTaaSService) VerifyDomainByDNS(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDomainByDNS", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyDomainByDNS indicates an expected call of VerifyDomainByDNS
func (mr *MockLTaaSServiceMockRecorder) VerifyDomainByDNS(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDomainByDNS", reflect.TypeOf((*MockLTaaSService)(nil).VerifyDomainByDNS), arg0)
}

// VerifyDomainByFile mocks base method
func (m *MockLTaaSService) VerifyDomainByFile(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDomainByFile", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyDomainByFile indicates an expected call of VerifyDomainByFile
func (mr *MockLTaaSServiceMockRecorder) VerifyDomainByFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDomainByFile", reflect.TypeOf((*MockLTaaSService)(nil).VerifyDomainByFile), arg0)
}
