// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ans-group/cli/internal/pkg/resource (interfaces: ResourceLocatorProvider)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockResourceLocatorProvider is a mock of ResourceLocatorProvider interface.
type MockResourceLocatorProvider struct {
	ctrl     *gomock.Controller
	recorder *MockResourceLocatorProviderMockRecorder
}

// MockResourceLocatorProviderMockRecorder is the mock recorder for MockResourceLocatorProvider.
type MockResourceLocatorProviderMockRecorder struct {
	mock *MockResourceLocatorProvider
}

// NewMockResourceLocatorProvider creates a new mock instance.
func NewMockResourceLocatorProvider(ctrl *gomock.Controller) *MockResourceLocatorProvider {
	mock := &MockResourceLocatorProvider{ctrl: ctrl}
	mock.recorder = &MockResourceLocatorProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceLocatorProvider) EXPECT() *MockResourceLocatorProviderMockRecorder {
	return m.recorder
}

// Locate mocks base method.
func (m *MockResourceLocatorProvider) Locate(arg0, arg1 string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locate", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Locate indicates an expected call of Locate.
func (mr *MockResourceLocatorProviderMockRecorder) Locate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locate", reflect.TypeOf((*MockResourceLocatorProvider)(nil).Locate), arg0, arg1)
}

// SupportedProperties mocks base method.
func (m *MockResourceLocatorProvider) SupportedProperties() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedProperties")
	ret0, _ := ret[0].([]string)
	return ret0
}

// SupportedProperties indicates an expected call of SupportedProperties.
func (mr *MockResourceLocatorProviderMockRecorder) SupportedProperties() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedProperties", reflect.TypeOf((*MockResourceLocatorProvider)(nil).SupportedProperties))
}
