// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ukfast/sdk-go/pkg/service/threatmonitoring (interfaces: ThreatMonitoringService)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	connection "github.com/ukfast/sdk-go/pkg/connection"
	threatmonitoring "github.com/ukfast/sdk-go/pkg/service/threatmonitoring"
	reflect "reflect"
)

// MockThreatMonitoringService is a mock of ThreatMonitoringService interface
type MockThreatMonitoringService struct {
	ctrl     *gomock.Controller
	recorder *MockThreatMonitoringServiceMockRecorder
}

// MockThreatMonitoringServiceMockRecorder is the mock recorder for MockThreatMonitoringService
type MockThreatMonitoringServiceMockRecorder struct {
	mock *MockThreatMonitoringService
}

// NewMockThreatMonitoringService creates a new mock instance
func NewMockThreatMonitoringService(ctrl *gomock.Controller) *MockThreatMonitoringService {
	mock := &MockThreatMonitoringService{ctrl: ctrl}
	mock.recorder = &MockThreatMonitoringServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockThreatMonitoringService) EXPECT() *MockThreatMonitoringServiceMockRecorder {
	return m.recorder
}

// GetAgent mocks base method
func (m *MockThreatMonitoringService) GetAgent(arg0 string) (threatmonitoring.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", arg0)
	ret0, _ := ret[0].(threatmonitoring.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgent indicates an expected call of GetAgent
func (mr *MockThreatMonitoringServiceMockRecorder) GetAgent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockThreatMonitoringService)(nil).GetAgent), arg0)
}

// GetAgents mocks base method
func (m *MockThreatMonitoringService) GetAgents(arg0 connection.APIRequestParameters) ([]threatmonitoring.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgents", arg0)
	ret0, _ := ret[0].([]threatmonitoring.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgents indicates an expected call of GetAgents
func (mr *MockThreatMonitoringServiceMockRecorder) GetAgents(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgents", reflect.TypeOf((*MockThreatMonitoringService)(nil).GetAgents), arg0)
}

// GetAgentsPaginated mocks base method
func (m *MockThreatMonitoringService) GetAgentsPaginated(arg0 connection.APIRequestParameters) (*threatmonitoring.PaginatedAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentsPaginated", arg0)
	ret0, _ := ret[0].(*threatmonitoring.PaginatedAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentsPaginated indicates an expected call of GetAgentsPaginated
func (mr *MockThreatMonitoringServiceMockRecorder) GetAgentsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentsPaginated", reflect.TypeOf((*MockThreatMonitoringService)(nil).GetAgentsPaginated), arg0)
}

// GetAlert mocks base method
func (m *MockThreatMonitoringService) GetAlert(arg0 string) (threatmonitoring.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlert", arg0)
	ret0, _ := ret[0].(threatmonitoring.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlert indicates an expected call of GetAlert
func (mr *MockThreatMonitoringServiceMockRecorder) GetAlert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlert", reflect.TypeOf((*MockThreatMonitoringService)(nil).GetAlert), arg0)
}

// GetAlerts mocks base method
func (m *MockThreatMonitoringService) GetAlerts(arg0 connection.APIRequestParameters) ([]threatmonitoring.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlerts", arg0)
	ret0, _ := ret[0].([]threatmonitoring.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlerts indicates an expected call of GetAlerts
func (mr *MockThreatMonitoringServiceMockRecorder) GetAlerts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlerts", reflect.TypeOf((*MockThreatMonitoringService)(nil).GetAlerts), arg0)
}

// GetAlertsPaginated mocks base method
func (m *MockThreatMonitoringService) GetAlertsPaginated(arg0 connection.APIRequestParameters) (*threatmonitoring.PaginatedAlert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlertsPaginated", arg0)
	ret0, _ := ret[0].(*threatmonitoring.PaginatedAlert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlertsPaginated indicates an expected call of GetAlertsPaginated
func (mr *MockThreatMonitoringServiceMockRecorder) GetAlertsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlertsPaginated", reflect.TypeOf((*MockThreatMonitoringService)(nil).GetAlertsPaginated), arg0)
}
