// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ans-group/sdk-go/pkg/service/pss (interfaces: PSSService)

// Package mocks is a generated GoMock package.
package mocks

import (
	connection "github.com/ans-group/sdk-go/pkg/connection"
	pss "github.com/ans-group/sdk-go/pkg/service/pss"
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
)

// MockPSSService is a mock of PSSService interface.
type MockPSSService struct {
	ctrl     *gomock.Controller
	recorder *MockPSSServiceMockRecorder
}

// MockPSSServiceMockRecorder is the mock recorder for MockPSSService.
type MockPSSServiceMockRecorder struct {
	mock *MockPSSService
}

// NewMockPSSService creates a new mock instance.
func NewMockPSSService(ctrl *gomock.Controller) *MockPSSService {
	mock := &MockPSSService{ctrl: ctrl}
	mock.recorder = &MockPSSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPSSService) EXPECT() *MockPSSServiceMockRecorder {
	return m.recorder
}

// CreateRequest mocks base method.
func (m *MockPSSService) CreateRequest(arg0 pss.CreateRequestRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRequest", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRequest indicates an expected call of CreateRequest.
func (mr *MockPSSServiceMockRecorder) CreateRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRequest", reflect.TypeOf((*MockPSSService)(nil).CreateRequest), arg0)
}

// CreateRequestFeedback mocks base method.
func (m *MockPSSService) CreateRequestFeedback(arg0 int, arg1 pss.CreateFeedbackRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRequestFeedback", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRequestFeedback indicates an expected call of CreateRequestFeedback.
func (mr *MockPSSServiceMockRecorder) CreateRequestFeedback(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRequestFeedback", reflect.TypeOf((*MockPSSService)(nil).CreateRequestFeedback), arg0, arg1)
}

// CreateRequestReply mocks base method.
func (m *MockPSSService) CreateRequestReply(arg0 int, arg1 pss.CreateReplyRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRequestReply", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRequestReply indicates an expected call of CreateRequestReply.
func (mr *MockPSSServiceMockRecorder) CreateRequestReply(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRequestReply", reflect.TypeOf((*MockPSSService)(nil).CreateRequestReply), arg0, arg1)
}

// DeleteReplyAttachment mocks base method.
func (m *MockPSSService) DeleteReplyAttachment(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReplyAttachment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReplyAttachment indicates an expected call of DeleteReplyAttachment.
func (mr *MockPSSServiceMockRecorder) DeleteReplyAttachment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReplyAttachment", reflect.TypeOf((*MockPSSService)(nil).DeleteReplyAttachment), arg0, arg1)
}

// DownloadReplyAttachmentStream mocks base method.
func (m *MockPSSService) DownloadReplyAttachmentStream(arg0, arg1 string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadReplyAttachmentStream", arg0, arg1)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadReplyAttachmentStream indicates an expected call of DownloadReplyAttachmentStream.
func (mr *MockPSSServiceMockRecorder) DownloadReplyAttachmentStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadReplyAttachmentStream", reflect.TypeOf((*MockPSSService)(nil).DownloadReplyAttachmentStream), arg0, arg1)
}

// GetCaseCategories mocks base method.
func (m *MockPSSService) GetCaseCategories(arg0 connection.APIRequestParameters) ([]pss.CaseCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaseCategories", arg0)
	ret0, _ := ret[0].([]pss.CaseCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaseCategories indicates an expected call of GetCaseCategories.
func (mr *MockPSSServiceMockRecorder) GetCaseCategories(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaseCategories", reflect.TypeOf((*MockPSSService)(nil).GetCaseCategories), arg0)
}

// GetCaseCategoriesPaginated mocks base method.
func (m *MockPSSService) GetCaseCategoriesPaginated(arg0 connection.APIRequestParameters) (*connection.Paginated[pss.CaseCategory], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCaseCategoriesPaginated", arg0)
	ret0, _ := ret[0].(*connection.Paginated[pss.CaseCategory])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCaseCategoriesPaginated indicates an expected call of GetCaseCategoriesPaginated.
func (mr *MockPSSServiceMockRecorder) GetCaseCategoriesPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCaseCategoriesPaginated", reflect.TypeOf((*MockPSSService)(nil).GetCaseCategoriesPaginated), arg0)
}

// GetChangeCases mocks base method.
func (m *MockPSSService) GetChangeCases(arg0 connection.APIRequestParameters) ([]pss.ChangeCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangeCases", arg0)
	ret0, _ := ret[0].([]pss.ChangeCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangeCases indicates an expected call of GetChangeCases.
func (mr *MockPSSServiceMockRecorder) GetChangeCases(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangeCases", reflect.TypeOf((*MockPSSService)(nil).GetChangeCases), arg0)
}

// GetChangeCasesPaginated mocks base method.
func (m *MockPSSService) GetChangeCasesPaginated(arg0 connection.APIRequestParameters) (*connection.Paginated[pss.ChangeCase], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangeCasesPaginated", arg0)
	ret0, _ := ret[0].(*connection.Paginated[pss.ChangeCase])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangeCasesPaginated indicates an expected call of GetChangeCasesPaginated.
func (mr *MockPSSServiceMockRecorder) GetChangeCasesPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangeCasesPaginated", reflect.TypeOf((*MockPSSService)(nil).GetChangeCasesPaginated), arg0)
}

// GetChangeImpactCaseOptions mocks base method.
func (m *MockPSSService) GetChangeImpactCaseOptions(arg0 connection.APIRequestParameters) ([]pss.CaseOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangeImpactCaseOptions", arg0)
	ret0, _ := ret[0].([]pss.CaseOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangeImpactCaseOptions indicates an expected call of GetChangeImpactCaseOptions.
func (mr *MockPSSServiceMockRecorder) GetChangeImpactCaseOptions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangeImpactCaseOptions", reflect.TypeOf((*MockPSSService)(nil).GetChangeImpactCaseOptions), arg0)
}

// GetChangeImpactCaseOptionsPaginated mocks base method.
func (m *MockPSSService) GetChangeImpactCaseOptionsPaginated(arg0 connection.APIRequestParameters) (*connection.Paginated[pss.CaseOption], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangeImpactCaseOptionsPaginated", arg0)
	ret0, _ := ret[0].(*connection.Paginated[pss.CaseOption])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangeImpactCaseOptionsPaginated indicates an expected call of GetChangeImpactCaseOptionsPaginated.
func (mr *MockPSSServiceMockRecorder) GetChangeImpactCaseOptionsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangeImpactCaseOptionsPaginated", reflect.TypeOf((*MockPSSService)(nil).GetChangeImpactCaseOptionsPaginated), arg0)
}

// GetChangeRiskCaseOptions mocks base method.
func (m *MockPSSService) GetChangeRiskCaseOptions(arg0 connection.APIRequestParameters) ([]pss.CaseOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangeRiskCaseOptions", arg0)
	ret0, _ := ret[0].([]pss.CaseOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangeRiskCaseOptions indicates an expected call of GetChangeRiskCaseOptions.
func (mr *MockPSSServiceMockRecorder) GetChangeRiskCaseOptions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangeRiskCaseOptions", reflect.TypeOf((*MockPSSService)(nil).GetChangeRiskCaseOptions), arg0)
}

// GetChangeRiskCaseOptionsPaginated mocks base method.
func (m *MockPSSService) GetChangeRiskCaseOptionsPaginated(arg0 connection.APIRequestParameters) (*connection.Paginated[pss.CaseOption], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangeRiskCaseOptionsPaginated", arg0)
	ret0, _ := ret[0].(*connection.Paginated[pss.CaseOption])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangeRiskCaseOptionsPaginated indicates an expected call of GetChangeRiskCaseOptionsPaginated.
func (mr *MockPSSServiceMockRecorder) GetChangeRiskCaseOptionsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangeRiskCaseOptionsPaginated", reflect.TypeOf((*MockPSSService)(nil).GetChangeRiskCaseOptionsPaginated), arg0)
}

// GetIncidentCase mocks base method.
func (m *MockPSSService) GetIncidentCase(arg0 string) (pss.IncidentCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentCase", arg0)
	ret0, _ := ret[0].(pss.IncidentCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentCase indicates an expected call of GetIncidentCase.
func (mr *MockPSSServiceMockRecorder) GetIncidentCase(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentCase", reflect.TypeOf((*MockPSSService)(nil).GetIncidentCase), arg0)
}

// GetIncidentCases mocks base method.
func (m *MockPSSService) GetIncidentCases(arg0 connection.APIRequestParameters) ([]pss.IncidentCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentCases", arg0)
	ret0, _ := ret[0].([]pss.IncidentCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentCases indicates an expected call of GetIncidentCases.
func (mr *MockPSSServiceMockRecorder) GetIncidentCases(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentCases", reflect.TypeOf((*MockPSSService)(nil).GetIncidentCases), arg0)
}

// GetIncidentCasesPaginated mocks base method.
func (m *MockPSSService) GetIncidentCasesPaginated(arg0 connection.APIRequestParameters) (*connection.Paginated[pss.IncidentCase], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentCasesPaginated", arg0)
	ret0, _ := ret[0].(*connection.Paginated[pss.IncidentCase])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentCasesPaginated indicates an expected call of GetIncidentCasesPaginated.
func (mr *MockPSSServiceMockRecorder) GetIncidentCasesPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentCasesPaginated", reflect.TypeOf((*MockPSSService)(nil).GetIncidentCasesPaginated), arg0)
}

// GetIncidentImpactCaseOptions mocks base method.
func (m *MockPSSService) GetIncidentImpactCaseOptions(arg0 connection.APIRequestParameters) ([]pss.CaseOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentImpactCaseOptions", arg0)
	ret0, _ := ret[0].([]pss.CaseOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentImpactCaseOptions indicates an expected call of GetIncidentImpactCaseOptions.
func (mr *MockPSSServiceMockRecorder) GetIncidentImpactCaseOptions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentImpactCaseOptions", reflect.TypeOf((*MockPSSService)(nil).GetIncidentImpactCaseOptions), arg0)
}

// GetIncidentImpactCaseOptionsPaginated mocks base method.
func (m *MockPSSService) GetIncidentImpactCaseOptionsPaginated(arg0 connection.APIRequestParameters) (*connection.Paginated[pss.CaseOption], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentImpactCaseOptionsPaginated", arg0)
	ret0, _ := ret[0].(*connection.Paginated[pss.CaseOption])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentImpactCaseOptionsPaginated indicates an expected call of GetIncidentImpactCaseOptionsPaginated.
func (mr *MockPSSServiceMockRecorder) GetIncidentImpactCaseOptionsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentImpactCaseOptionsPaginated", reflect.TypeOf((*MockPSSService)(nil).GetIncidentImpactCaseOptionsPaginated), arg0)
}

// GetIncidentTypeCaseOptions mocks base method.
func (m *MockPSSService) GetIncidentTypeCaseOptions(arg0 connection.APIRequestParameters) ([]pss.CaseOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentTypeCaseOptions", arg0)
	ret0, _ := ret[0].([]pss.CaseOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentTypeCaseOptions indicates an expected call of GetIncidentTypeCaseOptions.
func (mr *MockPSSServiceMockRecorder) GetIncidentTypeCaseOptions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentTypeCaseOptions", reflect.TypeOf((*MockPSSService)(nil).GetIncidentTypeCaseOptions), arg0)
}

// GetIncidentTypeCaseOptionsPaginated mocks base method.
func (m *MockPSSService) GetIncidentTypeCaseOptionsPaginated(arg0 connection.APIRequestParameters) (*connection.Paginated[pss.CaseOption], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentTypeCaseOptionsPaginated", arg0)
	ret0, _ := ret[0].(*connection.Paginated[pss.CaseOption])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentTypeCaseOptionsPaginated indicates an expected call of GetIncidentTypeCaseOptionsPaginated.
func (mr *MockPSSServiceMockRecorder) GetIncidentTypeCaseOptionsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentTypeCaseOptionsPaginated", reflect.TypeOf((*MockPSSService)(nil).GetIncidentTypeCaseOptionsPaginated), arg0)
}

// GetProblemCases mocks base method.
func (m *MockPSSService) GetProblemCases(arg0 connection.APIRequestParameters) ([]pss.ProblemCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblemCases", arg0)
	ret0, _ := ret[0].([]pss.ProblemCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblemCases indicates an expected call of GetProblemCases.
func (mr *MockPSSServiceMockRecorder) GetProblemCases(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblemCases", reflect.TypeOf((*MockPSSService)(nil).GetProblemCases), arg0)
}

// GetProblemCasesPaginated mocks base method.
func (m *MockPSSService) GetProblemCasesPaginated(arg0 connection.APIRequestParameters) (*connection.Paginated[pss.ProblemCase], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProblemCasesPaginated", arg0)
	ret0, _ := ret[0].(*connection.Paginated[pss.ProblemCase])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProblemCasesPaginated indicates an expected call of GetProblemCasesPaginated.
func (mr *MockPSSServiceMockRecorder) GetProblemCasesPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProblemCasesPaginated", reflect.TypeOf((*MockPSSService)(nil).GetProblemCasesPaginated), arg0)
}

// GetReply mocks base method.
func (m *MockPSSService) GetReply(arg0 string) (pss.Reply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReply", arg0)
	ret0, _ := ret[0].(pss.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReply indicates an expected call of GetReply.
func (mr *MockPSSServiceMockRecorder) GetReply(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReply", reflect.TypeOf((*MockPSSService)(nil).GetReply), arg0)
}

// GetRequest mocks base method.
func (m *MockPSSService) GetRequest(arg0 int) (pss.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequest", arg0)
	ret0, _ := ret[0].(pss.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequest indicates an expected call of GetRequest.
func (mr *MockPSSServiceMockRecorder) GetRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequest", reflect.TypeOf((*MockPSSService)(nil).GetRequest), arg0)
}

// GetRequestConversation mocks base method.
func (m *MockPSSService) GetRequestConversation(arg0 int, arg1 connection.APIRequestParameters) ([]pss.Reply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestConversation", arg0, arg1)
	ret0, _ := ret[0].([]pss.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequestConversation indicates an expected call of GetRequestConversation.
func (mr *MockPSSServiceMockRecorder) GetRequestConversation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestConversation", reflect.TypeOf((*MockPSSService)(nil).GetRequestConversation), arg0, arg1)
}

// GetRequestConversationPaginated mocks base method.
func (m *MockPSSService) GetRequestConversationPaginated(arg0 int, arg1 connection.APIRequestParameters) (*connection.Paginated[pss.Reply], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestConversationPaginated", arg0, arg1)
	ret0, _ := ret[0].(*connection.Paginated[pss.Reply])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequestConversationPaginated indicates an expected call of GetRequestConversationPaginated.
func (mr *MockPSSServiceMockRecorder) GetRequestConversationPaginated(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestConversationPaginated", reflect.TypeOf((*MockPSSService)(nil).GetRequestConversationPaginated), arg0, arg1)
}

// GetRequestFeedback mocks base method.
func (m *MockPSSService) GetRequestFeedback(arg0 int) (pss.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestFeedback", arg0)
	ret0, _ := ret[0].(pss.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequestFeedback indicates an expected call of GetRequestFeedback.
func (mr *MockPSSServiceMockRecorder) GetRequestFeedback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestFeedback", reflect.TypeOf((*MockPSSService)(nil).GetRequestFeedback), arg0)
}

// GetRequestReplies mocks base method.
func (m *MockPSSService) GetRequestReplies(arg0 int, arg1 connection.APIRequestParameters) ([]pss.Reply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestReplies", arg0, arg1)
	ret0, _ := ret[0].([]pss.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequestReplies indicates an expected call of GetRequestReplies.
func (mr *MockPSSServiceMockRecorder) GetRequestReplies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestReplies", reflect.TypeOf((*MockPSSService)(nil).GetRequestReplies), arg0, arg1)
}

// GetRequestRepliesPaginated mocks base method.
func (m *MockPSSService) GetRequestRepliesPaginated(arg0 int, arg1 connection.APIRequestParameters) (*connection.Paginated[pss.Reply], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestRepliesPaginated", arg0, arg1)
	ret0, _ := ret[0].(*connection.Paginated[pss.Reply])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequestRepliesPaginated indicates an expected call of GetRequestRepliesPaginated.
func (mr *MockPSSServiceMockRecorder) GetRequestRepliesPaginated(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestRepliesPaginated", reflect.TypeOf((*MockPSSService)(nil).GetRequestRepliesPaginated), arg0, arg1)
}

// GetRequests mocks base method.
func (m *MockPSSService) GetRequests(arg0 connection.APIRequestParameters) ([]pss.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequests", arg0)
	ret0, _ := ret[0].([]pss.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequests indicates an expected call of GetRequests.
func (mr *MockPSSServiceMockRecorder) GetRequests(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequests", reflect.TypeOf((*MockPSSService)(nil).GetRequests), arg0)
}

// GetRequestsPaginated mocks base method.
func (m *MockPSSService) GetRequestsPaginated(arg0 connection.APIRequestParameters) (*connection.Paginated[pss.Request], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestsPaginated", arg0)
	ret0, _ := ret[0].(*connection.Paginated[pss.Request])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequestsPaginated indicates an expected call of GetRequestsPaginated.
func (mr *MockPSSServiceMockRecorder) GetRequestsPaginated(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestsPaginated", reflect.TypeOf((*MockPSSService)(nil).GetRequestsPaginated), arg0)
}

// PatchRequest mocks base method.
func (m *MockPSSService) PatchRequest(arg0 int, arg1 pss.PatchRequestRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchRequest indicates an expected call of PatchRequest.
func (mr *MockPSSServiceMockRecorder) PatchRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchRequest", reflect.TypeOf((*MockPSSService)(nil).PatchRequest), arg0, arg1)
}

// UploadReplyAttachmentStream mocks base method.
func (m *MockPSSService) UploadReplyAttachmentStream(arg0, arg1 string, arg2 io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadReplyAttachmentStream", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadReplyAttachmentStream indicates an expected call of UploadReplyAttachmentStream.
func (mr *MockPSSServiceMockRecorder) UploadReplyAttachmentStream(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadReplyAttachmentStream", reflect.TypeOf((*MockPSSService)(nil).UploadReplyAttachmentStream), arg0, arg1, arg2)
}
